api_version: 1
runtime: php55
instance_class: F1
service: product-autosuggest

threadsafe: true

skip_files:
  - products.json
  
inbound_services:
- warmup

automatic_scaling:
  min_idle_instances: 1
  max_pending_latency: 1s
  
handlers:
# Load Cloud Datastore
- url: /tasks/loaddatastore
  script: schedule_load.php
  login: admin

# Warm up requests for Memcache
- url: /_ah/warmup
  script: warmup.php
  login: admin

# Cleanup Datastore Kind
- url: /_ah/delete_all
  script: delete_all.php
  login: admin

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
# Default page handler
- url: /.*
  script: form.html
